In [2]:
import numpy as np
import pandas as pd

In [3]:
from sklearn import datasets

iris = datasets.load_iris()

In [4]:
data1 = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])

In [5]:
data1

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
..      ...  
145     2.0  
146     2.0  
147     2.0  
148     2.0  
149     2.0  

[150 rows x 5 columns]

In [6]:
matrix=data1.corr()

# Ejercicio 1: 

Demuestra que la matriz de correlación es una matriz simétrica por los siguientes métodos

*Usando Trnaspuesta

*Usando las matrices triangulares

In [7]:
matrix1=matrix.T
matrix1

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   
target                      0.782561         -0.426658           0.949035   

                   petal width (cm)    target  
sepal length (cm)          0.817941  0.782561  
sepal width (cm)          -0.366126 -0.426658  
petal length (cm)          0.962865  0.949035  
petal width (cm)           1.000000  0.956547  
target                     0.956547  1.000000

In [8]:
mat2 = matrix1 == matrix1.T
mat2

#hacer ciclo  

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)               True              True               True   
sepal width (cm)                True              True               True   
petal length (cm)               True              True               True   
petal width (cm)                True              True               True   
target                          True              True               True   

                   petal width (cm)  target  
sepal length (cm)              True    True  
sepal width (cm)               True    True  
petal length (cm)              True    True  
petal width (cm)               True    True  
target                         True    True

In [9]:
matrixTabajo=np.triu(matrix,0)
matrixTabajo

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113,  0.78256123],
       [ 0.        ,  1.        , -0.4284401 , -0.36612593, -0.42665756],
       [ 0.        ,  0.        ,  1.        ,  0.96286543,  0.9490347 ],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.95654733],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ]])

In [10]:
matrixTarriba=np.tril(matrix,0)
matrixTarriba

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [-0.11756978,  1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.        ,  0.        ],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ,  0.        ],
       [ 0.78256123, -0.42665756,  0.9490347 ,  0.95654733,  1.        ]])

# Ejercicio 2
Obten la matriz inversa de la matriz de correlación

In [11]:
matrixInversa=np.linalg.inv(matrix)
matrixInversa

array([[  7.25653439,  -2.38831293, -11.4928302 ,   2.70178095,
          1.62503903],
       [ -2.38831293,   2.10740433,   4.83544897,  -2.22385256,
          0.30635248],
       [-11.4928302 ,   4.83544897,  34.74887396, -15.51696788,
         -7.07824868],
       [  2.70178095,  -2.22385256, -15.51696788,  20.70668693,
         -8.14391775],
       [  1.62503903,   0.30635248,  -7.07824868,  -8.14391775,
         14.36656146]])

# Ejercicio 3
¿Qué operación(es) harías para obtener la matriz identidad?

I=A * A**(-1)

In [12]:
matrix * matrixInversa

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           7.256534          0.280793         -10.018918   
sepal width (cm)            0.280793          2.107404          -2.071700   
petal length (cm)         -10.018918         -2.071700          34.748874   
petal width (cm)            2.209898          0.814210         -14.940752   
target                      1.271693         -0.130708          -6.717504   

                   petal width (cm)     target  
sepal length (cm)          2.209898   1.271693  
sepal width (cm)           0.814210  -0.130708  
petal length (cm)        -14.940752  -6.717504  
petal width (cm)          20.706687  -7.790043  
target                    -7.790043  14.366561

In [13]:
identidad=matrix.dot(matrixInversa)
identidad.round(2)

0    1    2    3    4
sepal length (cm)  1.0 -0.0  0.0  0.0  0.0
sepal width (cm)   0.0  1.0 -0.0  0.0  0.0
petal length (cm)  0.0 -0.0  1.0  0.0 -0.0
petal width (cm)   0.0 -0.0 -0.0  1.0  0.0
target             0.0 -0.0 -0.0  0.0  1.0